#!/usr/bin/env bash
set -euo pipefail

# ──────────────────────────────────────────────
#  Image2 MCP — One-Click Setup
#  Usage: bash scripts/setup.sh
# ──────────────────────────────────────────────

BOLD="\033[1m"
GREEN="\033[32m"
RED="\033[31m"
CYAN="\033[36m"
YELLOW="\033[33m"
RESET="\033[0m"

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$HOME/.claude/.env"
CLAUDE_JSON="$HOME/.claude.json"

echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BOLD}  Image2 MCP — One-Click Setup${RESET}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""

# ── 1. Install / check uv ─────────────────
echo -e "${BOLD}[1/5]${RESET} Ensuring uv is installed..."

UV_PATH=""

if command -v uv &>/dev/null; then
    UV_PATH="$(command -v uv)"
    echo -e "  ${GREEN}✓${RESET} uv $(uv --version) (at $UV_PATH)"
else
    echo -e "  ${YELLOW}!${RESET} uv not found — installing now..."
    case "$(uname -s)" in
        Darwin)
            echo -e "  Installing uv on macOS..."
            curl -LsSf https://astral.sh/uv/install.sh | sh
            ;;
        MINGW*|MSYS*|CYGWIN*)
            echo -e "  Installing uv on Windows..."
            powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
            ;;
        Linux)
            echo -e "  Installing uv on Linux..."
            curl -LsSf https://astral.sh/uv/install.sh | sh
            ;;
        *)
            echo -e "  ${RED}✗${RESET} Unknown OS — please install uv manually:"
            echo "    https://docs.astral.sh/uv/getting-started/installation/"
            echo ""
            exit 1
            ;;
    esac

    export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
    if command -v uv &>/dev/null; then
        UV_PATH="$(command -v uv)"
        echo -e "  ${GREEN}✓${RESET} uv installed successfully ($(uv --version))"
    else
        echo -e "  ${RED}✗${RESET} uv installation may have failed — restart your shell and re-run."
        exit 1
    fi
fi

# ── 2. Install dependencies ────────────────
echo -e "${BOLD}[2/5]${RESET} Installing Python dependencies..."
cd "$PROJECT_DIR"
uv sync
echo -e "  ${GREEN}✓${RESET} Dependencies installed"

# ── 3. API Key ─────────────────────────────
echo ""
echo -e "${BOLD}[3/5]${RESET} Configuring API key..."

MAGENE_API_KEY="${MAGENE_API_KEY:-}"

if [ -n "${MAGENE_API_KEY:-}" ]; then
    echo -e "  ${GREEN}✓${RESET} MAGENE_API_KEY already set in environment"
elif [ -f "$ENV_FILE" ] && grep -q "^MAGENE_API_KEY=" "$ENV_FILE" 2>/dev/null; then
    EXISTING_KEY=$(grep "^MAGENE_API_KEY=" "$ENV_FILE" | head -1 | cut -d'=' -f2-)
    if [ -n "$EXISTING_KEY" ] && [ "$EXISTING_KEY" != "sk-your-api-key-here" ]; then
        MAGENE_API_KEY="$EXISTING_KEY"
        echo -e "  ${GREEN}✓${RESET} MAGENE_API_KEY found in $ENV_FILE"
    else
        echo -n "  Enter your MAGENE_API_KEY: "
        read -r MAGENE_API_KEY
    fi
else
    echo -n "  Enter your MAGENE_API_KEY: "
    read -r MAGENE_API_KEY
fi

if [ -z "$MAGENE_API_KEY" ]; then
    echo -e "  ${RED}✗${RESET} No API key provided. Setup aborted."
    exit 1
fi

# ── 4. Write ~/.claude/.env ────────────────
echo ""
echo -e "${BOLD}[4/5]${RESET} Writing environment config..."

mkdir -p "$HOME/.claude"

# Use Python to safely write .env.
# Pass sensitive values via environment to avoid shell injection into Python source.
SETUP_API_KEY="$MAGENE_API_KEY" \
SETUP_ENV_FILE="$ENV_FILE" \
uv run python -c "
import os
import sys

env_file = os.environ['SETUP_ENV_FILE']
api_key = os.environ['SETUP_API_KEY']
base_url = 'http://tops.magene.cn:11636/api/v1/images/generations'

# Read existing entries (if file exists)
entries = {}
if os.path.exists(env_file):
    with open(env_file) as f:
        for line in f:
            line = line.rstrip('\n').rstrip('\r')
            if '=' in line and not line.startswith('#'):
                key, _, val = line.partition('=')
                entries[key.strip()] = val.strip()

# Update/add required keys
entries['MAGENE_API_KEY'] = api_key
entries['MAGENE_API_BASE_URL'] = base_url

# Write back (always ends with newline)
with open(env_file, 'w') as f:
    f.write('# Image2 MCP — Environment Configuration\n')
    f.write('# Auto-generated by setup.sh — do not edit manually\n')
    f.write('\n')
    for k, v in sorted(entries.items()):
        f.write(f'{k}={v}\n')

# Mask API key in output: show only prefix
masked = api_key[:4] + '****' + api_key[-4:] if len(api_key) > 8 else '****'
print(f'Wrote {env_file}')
print(f'MAGENE_API_KEY={masked}')
print(f'MAGENE_API_BASE_URL={base_url}')
" 2>&1 | while IFS= read -r line; do echo -e "  ${GREEN}✓ ${line}${RESET}"; done

# ── 5. Configure MCP server ────────────────
echo ""
echo -e "${BOLD}[5/5]${RESET} Configuring Claude Code MCP server..."

# Write MCP config to ~/.claude.json (NOT ~/.claude/.mcp.json — fixes 问题 3)
# Uses bash -c wrapper that sources ~/.claude/.env so API key is not duplicated in claude.json
SETUP_UV_PATH="$UV_PATH" \
SETUP_PROJECT_DIR="$PROJECT_DIR" \
SETUP_CLAUDE_JSON="$CLAUDE_JSON" \
uv run python -c "
import json, os, sys

claude_json = os.environ['SETUP_CLAUDE_JSON']
project_dir = os.environ['SETUP_PROJECT_DIR']
uv_path = os.environ['SETUP_UV_PATH']

entry = {
    'command': 'bash',
    'args': [
        '-c',
        'set -a; [ -f ~/.claude/.env ] && . ~/.claude/.env; [ -f .env ] && . ./.env; set +a; exec ' + uv_path + ' run --directory ' + project_dir + ' python -m image2_mcp'
    ],
    'env': {
        'PATH': os.path.expanduser('~/.local/bin') + ':/usr/local/bin:/usr/bin:/bin',
        'HOME': os.path.expanduser('~')
    },
    'description': '文生图 — 调用公司统一 API 平台 image2 模型生成图片',
    'type': 'stdio'
}

# Read ~/.claude.json
if os.path.exists(claude_json):
    with open(claude_json) as f:
        data = json.load(f)
else:
    data = {}

# Ensure mcpServers key exists at top level
if 'mcpServers' not in data:
    data['mcpServers'] = {}

if 'image2' in data['mcpServers']:
    print('! image2 entry already exists in ~/.claude.json, replacing...')
else:
    print('Adding image2 to ~/.claude.json...')

data['mcpServers']['image2'] = entry

with open(claude_json, 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write('\n')

print('image2 MCP server configured in ~/.claude.json')
print('Command: {}'.format(uv_path))
print('Project: {}'.format(project_dir))
print('API key is loaded from ~/.claude/.env at runtime (not stored here)')
" 2>&1 | while IFS= read -r line; do echo -e "  ${GREEN}✓ ${line}${RESET}"; done

# ── Health Check ───────────────────────────
echo ""
echo -e "${BOLD}Running health check...${RESET}"
echo ""

# Source env file for health check
set +u
if [ -f "$ENV_FILE" ]; then
    set -a
    . "$ENV_FILE"
    set +a
fi
set -u

if uv run --directory "$PROJECT_DIR" python -m image2_mcp --health-check; then
    echo ""
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${GREEN}${BOLD}  ✓ Setup complete!${RESET}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
    echo -e "  ${BOLD}Next:${RESET} Restart Claude Code, then try:"
    echo -e '    "帮我生成一张图片..."'
    echo ""
else
    echo ""
    echo -e "${YELLOW}${BOLD}  Setup finished with warnings.${RESET}"
    echo "  Check the output above for details."
    echo "  You may need to:"
    echo "    1. Verify your API key is valid"
    echo "    2. Check your network/VPN connection"
    echo "    3. Run: uv run --directory $PROJECT_DIR python -m image2_mcp --health-check"
    echo ""
fi
